name: Enforce Merge Method

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  enforce-merge-method:
    runs-on: ubuntu-latest
    steps:
      - name: Check merge method
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          TARGET_BRANCH="${{ github.base_ref }}"
          
          if [[ $BRANCH_NAME == hotfix/* ]]; then
            if [[ $(gh api repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }} --jq '.merge_method') != "merge" ]]; then
              echo "Hotfix branches must use merge commit method"
              exit 1
            fi
          else
            if [[ $(gh api repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }} --jq '.merge_method') != "squash" ]]; then
              echo "Regular branches must use squash merge method"
              exit 1
            fi
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
